# Generated by Django 2.0 on 2018-05-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bucketlist_no_of_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='itera',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='lear_rate',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
